### ISSUE TITLE
create worker in admin page

### ISSUE THREAD

**Issue by GuyAriol** [GuyAriol/isy-event#10]
### Tasks

- [ ] Create a worker for a given event
- [ ] Activate a worker card (reuse method from superAdmin)
- [ ] Delete worker
- [ ] Deactivate work card

### SW Req
an admin should be able to create worker with a corresponding role. Then activate a nfc card with those informations. The admin should be able to delete worker or deactivate worker card as well.
