### ISSUE TITLE
app login

### ISSUE THREAD

**Issue by GuyAriol** [GuyAriol/isy-event#2]
### Tasks
- [ ] Authentification caissier boissons (vente boisson, _user type 1_)

- [ ] Authentification barman (sortie boisson, _user type 2_)

- [ ] Authentification Admin (Boss, _admin_)

- [ ] Authentification vendeur ticket (vente ticket d'entrée et boisson table, _user type 3_)

### SW Req

- chaque utilisateur débloque son terminal avec sa carte

- une carte utilisateur débloque un seul terminal

- la carte admin débloque tous les terminaux
