### ISSUE TITLE
NFC read - event subscription

### ISSUE THREAD

**Issue by GuyAriol** [GuyAriol/isy-event#3]
### Tasks
- [ ] subscribe to nfc read event (method)
- [ ] decrypt a given encrypted nfc payload (method)
- [ ] unsubscribe to nfc read event (method)

### SW Req
**By every nfc tag:**
      1. show loading spinner 
      2. read the card content
      3. trigger a nfcRead handler and pass the card content as argument.
