### ISSUE TITLE
nfc write

### ISSUE THREAD

**Issue by GuyAriol** [GuyAriol/isy-event#4]
### Tasks

- [ ] write a given encrypted payload to nfc card (method)
- [ ] encrypt a given string (method)
- [ ] build the nfc payload, cmd+user role+balance (method)

### SW Req

- write an encrypted paylod to a nfc card when it is tapped
- nfc payload is build with cmd type, user role and actual balance
