### ISSUE TITLE
dialog provider

### ISSUE THREAD

**Issue by GuyAriol** [GuyAriol/isy-event#6]
### Tasks

- [ ] show loading spinner (method)
- [ ] dismiss loading spinner (method)
- [ ] show simple dialog pop up (method)
- [ ] translate and show authentification errors (method)
- [ ] show toast (method)

### SW Req

- generic way to show up an alert to the user
