### ISSUE TITLE
firebase login 

### ISSUE THREAD

**Issue by GuyAriol** [GuyAriol/isy-event#7]
### Tasks

- [ ] firebase user sign up (method) 
- [ ] firebase user sign in (method)
- [ ] firebase  user registration (method)

### SW Req

- to be able to write or read the database the user should be authentificated
