### ISSUE TITLE
Bluetooth COM

### ISSUE THREAD

**Issue by GuyAriol** [GuyAriol/isy-event#8]
### Tasks

- [ ] scan and discover devices with enabled bluetooth
- [ ] Connect devices to each other
- [ ] Disconnect device
- [ ] Catch broken connection 

### SW Req

- nfc terminal should send nfc card information to a display via bluetooth. One or more displays can be attached to a single nfc terminal
